### ISSUE TITLE
Plex module menu buttons not hidden when settings open

### ISSUE THREAD

**Issue by Wraithers** [gugahoi/maraschino#13]
As per the picture attached, you can see that the menu for the Plex module (top-right) shows up underneath the 'Settings' and 'Close' buttons. The latter are no longer clickable, unless I use the Inspector and hide the menu.

![screenshot 38](https://f.cloud.github.com/assets/4705057/2470584/52d200b2-b015-11e3-82a6-e8ec814d7cd9.png)

**Comment by gugahoi** [comment]
Yes, I am aware of this, should be fixed soon.

**Comment by Wraithers** [comment]
Fixed with the latest commit (0a9094de99dd946a12b5d16cab7baf71e1efe811)
