### ISSUE TITLE
Display issues with Plex module

### ISSUE THREAD

**Issue by Wraithers** [gugahoi/maraschino#14]
As per the picture attached, the Plex module seems to start up with the 'On Deck' view, however some images are either broken or missing. Is this a polling or request issue?

Also, as can be seen, the category names make each menu button very wide and causes it to go under the module name. Replacing them with icons would be best. Also, a menu button to go back to the 'On Deck' view is required.

![screenshot 36](https://f.cloud.github.com/assets/4705057/2470622/132e584c-b016-11e3-9e12-dbfd82d2b88f.png)

**Comment by gugahoi** [comment]
I will prob switch the menu to icons as I did think this kind of issue would arise with all the words. As per the broken images I am not sure, could you post the links to those images here? Do you have multiple plex servers?

I am happy for someone to send me some nice icons to use.

**Comment by gugahoi** [comment]
Another option would be to do like we have for XBMC - separate modules for your library, recently added movies, recently added tv and on deck. Do you think that would be better?

**Comment by Wraithers** [comment]
Ah, it seems the 'broken' image is because that file is missing a media thumbnail, so it's displaying that way. It might be good to use Plex's method of displaying a placeholder instead, they use this base64 image - http://pastebin.com/FEWefaje. However, the space on the left of the broken image is not linked to any media, it's just 4 blank spots. Not sure what's happening there.

I do have multiple Plex servers, but the other is on a different computer on the network, and does not show up in the Plex module's On Deck view. Thanks for pointing that out, seems like multiple servers needs to be tackled as well.

**Comment by Wraithers** [comment]
About the icons, you could use Font Awesome Icons - http://fortawesome.github.io/Font-Awesome/icons/. It's a CSS font implementation. Very easy to add to a web app, check Getting Started. If not, let me know, there are other icon packs I've bookmarked elsewhere.

I haven't used Maraschino the XBMC way, with the separate modules, so I can't comment on whether that would be good or not. If the purpose is to have Plex as the center of Maraschino, as is the case with the XBMC version, then maybe it does make sense to have them as separate modules.

Trying to think of use cases where having it all in one module would be better, only thing I can think of at the moment is that it saves space.

**Comment by gugahoi** [comment]
The problem for me at the moment is that I only access a single Plex Server so I dont have the resources to test multiple servers however I am keeping in mind that possibility and I can always have the same solution used for XBMC which would be having a drop down menu where the user can select which server to use or even have the user enable all the servers they want and I can fetch the library info for each and every one of them - this would prob put a big dent in load time, specially if the server is not local. Having that said I have already started to store all the server info in maraschino's db so should be good.

I will look into having a  "missing thumb" icon and I suspect the black spaces were under a "movie icon" and I am aware of that, have fixed it locally (I think).

**Comment by gugahoi** [comment]
The menu should be fixed now since I am using plex's built in icons and not words anymore. If you still have trouble with them let me know. Also note that this last push should not work with the previous db so I advise you to delete/backup the old one and start fresh.

**Comment by Wraithers** [comment]
I did a clean pull, started Maraschino up, entered my Plex username and password, and I get an error saying `No PlexServer in db. Please check your myPlex username and password`.

I checked my username and password by signing out of, then back in to Plex. Do I need to wait for it to poll the server and create it in the db and try later, or am I missing a step somewhere..?

**Comment by gugahoi** [comment]
By default I have maraschino poll whenever the plex module settings are saved or when maraschino starts up and every six hours maraschino is running. I select the server based on the "owned" property on plex's servers.xml file since that is how they do it with PHT, is it possible the user you are using does not "own" the server and it is simply shared with him? I also log when maraschino failed to authorise credentials with a "401 Unauthorised". A way to make sure the db was populated properly would be to get a sql db browser and check maraschino.db for server info. If you can jump on irc i'm at freenode @ #maraschino, might be easier to check whats going on this way.

**Comment by gugahoi** [comment]
@Wraithers - seems like I was able to get Maraschino running fine on windows 8.1 pro with only python 2.7.6. 

The last thing I can think of is unusual characters in your password for myPlex, to confirm that the info is stored correctly you will need a db viewer ([this one](http://sourceforge.net/projects/sqlitebrowser/) worked for me) and check if your username and password are stored properly under the settings table.

![screen shot 2014-03-21 at 3 45 24 pm](https://f.cloud.github.com/assets/355877/2480271/9544cd72-b0b4-11e3-8252-9967923b5ab5.png)

**Comment by Wraithers** [comment]
Ah, dang, sorry to put you through all that. Will check it out as soon as
I'm back at my PC.

Aaron Khare

**Comment by Wraithers** [comment]
Hey @gugahoi I used the db browser you recommended, and it showed my username and password under settings just as I write it, so that's not the issue.
![screenshot 42](https://f.cloud.github.com/assets/4705057/2482337/ffd85156-b0e9-11e3-9db3-0ec58bc56b8b.png)

The plexserver table is empty, btw. Should I try to manually add an entry?
If possible, let me know what else I should check/try. Thanks.
![screenshot 41](https://f.cloud.github.com/assets/4705057/2482340/2a40c54a-b0ea-11e3-8979-9a7b4bcf766b.png)

**Comment by Wraithers** [comment]
Also, I noticed the icons you used for the menu buttons, and I think you'd be better off using those with/for the module titles. In their place, look at Plex.tv/web (which will soon replace the default media manager), you can see they use the Bootstrap glyphicons in the left-hand side menu. You can get them [here](http://glyphicons.com/) - scroll down for the free set. Cheers =)

**Comment by gugahoi** [comment]
Those icons were just a temporary solution, I will look into using the bootstrap icons soon.
I am stumped by the problem you are having, altho I did find a minor bug in my code that I have now fixed locally. If you can jump back on irc I can guide you through some more troubleshooting steps.

**Comment by Wraithers** [comment]
Ah, cool. Yup, the icons aren't important right now, I saw the other todo
issues =)

Sure, I'll get on irc in 10 minutes.

Cheers,

Aaron K.

**Comment by Wraithers** [comment]
Fixed with the latest commit (0a9094de99dd946a12b5d16cab7baf71e1efe811)
