### ISSUE TITLE
Nzbdrone Support

### ISSUE THREAD

**Issue by vwieczorek** [gugahoi/maraschino#24]
Would love to see this added: http://nzbdrone.com/

Thanks for the great software!

**Comment by gugahoi** [comment]
I would love to add it too and plan on doing it eventually. At the moment I am focusing on implementing plex functionality tho so my focus is on that and it might take a while to finish it off.

**Comment by gugahoi** [comment]
This is in the pipeline so I'm closing it. Check out the nzbdrone branch if you wish to.
