### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by olavimmanuel** [gugahoi/maraschino#25]
The mobile web page is not loading for me.
e.g.: http://127.0.0.1:7000/mobile

**Comment by gugahoi** [comment]
It was deactivated while I was changing from XBMC to Plex, just put it back now.

**Comment by olavimmanuel** [comment]
Thank you! :smile:

**Comment by olavimmanuel** [comment]
Do you have plans to add the plex modules to mobile view as well?

**Comment by gugahoi** [comment]
Sure, eventually, need to get the desktop interface in top shape first.
