### ISSUE TITLE
initd error

### ISSUE THREAD

**Issue by chimpy** [gugahoi/maraschino#28]
Thanks for the great Plex port! Not sure whether I should open this issue here or over at mrkiplings place, so feel free to tell me off.

I cloned the latest version from here and placed default in /etc/default/maraschino and initd in /etc/init.d/maraschino.

I started it up via the init script and got:

```
/etc/init.d/maraschino: 83: [: -eq: unexpected operator
```

Line 83 is:

``` bash
[ $KIOSK -eq 1 ] && DAEMON_OPTS="$DAEMON_OPTS --kiosk"
```

This happens because the KIOSK variable is commented in the default file, meaning $KIOSK evaluates to null.

It seems that the solution is either to uncomment KIOSK in default (lazy solution), or set it to 0 if it evaluates to null:

``` bash
[ ${KIOSK:-0} -eq 1 ] && DAEMON_OPTS="$DAEMON_OPTS --kiosk"
```

**Comment by gugahoi** [comment]
I think this was fixed with a recent commit. Please let me know if this is not the case.

**Comment by chimpy** [comment]
As soon as it gets working for the sb fork I'll test it! :)

Sent from my iPhone

> On 25 août 2014, at 16:21, Gustavo Hoirisch
