### ISSUE TITLE
DNS and SickBeard Suggestion 

### ISSUE THREAD

**Issue by Madseason41** [gugahoi/maraschino#31]
First off let me say that this is an awesome tool. I have been using SB, CP, HP, ad PLEX for a while and just recently stumbled across Maraschino.

To the original dev and the PLEX version dev. Hats off.

To further increase my enjoyment of this app.....

Due to network restrictions I must use local IP addresses when acessing apps from my local network and use a dns when outside the local network. Is there any chance to add a setting for DNS addresses in each module and have it use this address with the port number when being accesses from an outside network? Or is does this functionality all ready exist? OR is it it even possible?

So lets say I access maraschino via dns from a random computer at work, and then open sick beard via maraschino, it would thus open sick beard using the dns address instead of my local IP that is in settings. I have only tried this with the sick beard module and it tried to open the local ip address which of course would not work.

I know you are aware of the SickRage api call change issue and are working it. Any chance to make this a separate module for people that are using multiple sick beard programs at one time?

Thanks for the great work!

**Comment by Madseason41** [comment]
I believe this link alludes to being able to identify if a request comes from a local or external network. I may be wrong...
http://stackoverflow.com/questions/9092376/identify-if-request-is-coming-from-local-network-intranet

**Comment by gugahoi** [comment]
Cant you use the DNS address all times? This is what I do and that means links will work no matter where I access from. I believe if the router recognises the address you are accessing is itself it wont really go out of the network and waste bandwidth if thats what you are worried about.

**Comment by dannyb78** [comment]
you're right gugahoi. This must works.
Depending on your router you could also use dns names, it will redirect in local addresses the name too if dns is well configured.

**Comment by Madseason41** [comment]
Can't because of NAT loopback. No worries I just created two applications for each. One with local Ip and one with DNS.

Thanks.

**Comment by Madseason41** [comment]
Well I finally got around to digging into my NAT loopback issues. I haven't been able to get it to work and I always assumed it was due to ISP provider restrictions. After digging deeper I discovered my modem was not in bridge mode. So after straightening all that out I no longer have NAT loopback problems and feel like a DA for even suggesting the improvement. 

This can/ should be closed unless you want to leave it open for the multiple Sickbeard fork suggestion.

Thanks

**Comment by gugahoi** [comment]
That's good to hear! I am not sure how feasible it would be to support SickRage. How often does his API change?

**Comment by Madseason41** [comment]
I'm not sure how often it changes but it does seem to be catching on and has a lot of great features.

**Comment by gugahoi** [comment]
Ye I agree it doe shave some great features, I used it for a couple of weeks. However it seems to be a consensus that SickRage is a little messy in it's code structure and this worries me because if I do spend my time developing something for it and then it doesnt work I will be upset. I can always put it on the bottom of my TODO list for now and if/when I get around to it I'll try to push something for it :smiley:

**Comment by gugahoi** [comment]
So there's another SickRage request and someone is working on a module for it. I'm closing this one.
