### ISSUE TITLE
nzbdrone title goes to maraschino page, not nzbdrone

### ISSUE THREAD

**Issue by troycarpenter** [gugahoi/maraschino#32]
nzbdrone module configured and working.  However, when I click on the nzbdrone title, it goes to maraschino page instead of nzbdrone.

Specifically, the link in the title appears to be using maraschino's port number instead of nzbdrone's port number.

**Comment by gugahoi** [comment]
Should be fixed

**Comment by troycarpenter** [comment]
Confirmed Fixed.
