### ISSUE TITLE
Improper Syntax to Grab NZBDrone Cover Art

### ISSUE THREAD

**Issue by Needle2000** [gugahoi/maraschino#35]
nzbdrone.html Line 17

was {{ episode.series.images.0 if episode.series.images.0 }}
should be {{ episode.series.images.0.url if episode.series.images.0 }}

**Comment by gugahoi** [comment]
Thanks for this, I will fix it now!
Also seemed to help the nzbdrone people as there was a bug in the latest develop version when I was making this change that revealed the api call was actually not returning anything for the images!
